package ren.oliver.bos.sao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-15T09:13:12.945+08:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "CustomerServiceImplService",
                  wsdlLocation = "http://localhost:8080/CRM/service/customerService?wsdl",
                  targetNamespace = "http://impl.service.crm.oliver.ren/")
public class CustomerServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.crm.oliver.ren/", "CustomerServiceImplService");
    public final static QName CustomerServiceImplPort = new QName("http://impl.service.crm.oliver.ren/", "CustomerServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CRM/service/customerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CRM/service/customerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceImplPort")
    public CustomerService getCustomerServiceImplPort() {
        return super.getPort(CustomerServiceImplPort, CustomerService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceImplPort")
    public CustomerService getCustomerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerServiceImplPort, CustomerService.class, features);
    }

}
